### PR TITLE
fix: Update manifests to include url parameter

### PR DESCRIPTION
**Pull request by bradbeam**
Missed regenerating the manifests in #127 

Signed-off-by: Brad Beam <brad.beam@carbonrelay.com>

### CODE REVIEW

**Comment by bradbeam** [comment]
need to find a good way to catch this

**Review by jgustie — APPROVED** [review]
We need to stop committing the `zz_generated.output.go` otherwise the repository size is going to skyrocket.

**Comment by bradbeam** [comment]
> We need to stop committing the zz_generated.output.go otherwise the repository size is going to skyrocket.

as in have this file get generated during build time?

**Comment by jgustie** [comment]
Correct, otherwise we get saddled with a 100K change set in Git for every 20 byte change to a configuration manifest. Those large change sets are unavoidable in history and the Git repository size balloons.

**Comment by andrewhare** [comment]
Can you add it to the gitignore for now?

**Comment by bradbeam** [comment]
I think we tried it at one point and backed off because of the additional time it took.. or was that `conversion_gen`?

I'll update this pr and give it a shot.

**Comment by bradbeam** [comment]
Updated and I think we're still in business.

**Review by jgustie — APPROVED** [review]

**Pull request merged**
