### PR TITLE
Support reporting more trial failure information to API

### PR DESCRIPTION
**Pull request by jameshochadel**

### CODE REVIEW

**Comment by jameshochadel** [comment]
Let me know if my approach with the `go.mod` makes sense. Thanks!

**Comment by jameshochadel** [comment]
When I try to run `make generate` to fix the failing check, I get the following error: 

```
# github.com/redskyops/redskyops-controller/redskyctl/internal/kustomize
redskyctl/internal/kustomize/assets.go:39:12: undefined: kustomizeBase
make: *** [generate-docs] Error 2
```

That file, `assets.go`, does indeed contain these lines: 

```go
var Assets = map[string]*Asset{
	"stock": &kustomizeBase,
}
```

And `kustomizeBase` is not defined anywhere. Is this another layer of codegen I'm missing somewhere?

**Review by bradbeam — DISMISSED** [review]
unsure if we want to cut a new client release or just use the fake version for now.

**Review by jgustie — APPROVED** [review]

**Comment by jgustie** [comment]
Let's wait for the backed updates to be rolled out before merging this.

**Comment by jameshochadel** [comment]
Backend updates have rolled out; pending further comment, I'll merge this tomorrow.

**Pull request merged**
